version: '2'

networks:
  test:

services: 
  ca_org3_peer:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca 
      - FABRIC_CA_SERVER_CA_NAME=ca_org3_peer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=6054
    ports:
      - "6054:6054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/CAs/peers/org3:/etc/hyperledger/fabric-ca
    container_name: ca_org3_peer
    networks:
      - test