# Copyright IBM Corp. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

version: '2'

networks:
  test:

services:
  couchdb2:
    container_name: couchdb2
    image: couchdb:3.1.1
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "4984:5984"
    networks:
      - test

  couchdb3:
    container_name: couchdb3
    image: couchdb:3.1.1
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "5984:5984"
    networks:
      - test