version: '2'

networks:
  test:

services: 
  ca_org2_peer:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca 
      - FABRIC_CA_SERVER_CA_NAME=ca_org2_peer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=4054
    ports:
      - "4054:4054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/CAs/peers/org2:/etc/hyperledger/fabric-ca
    container_name: ca_org2_peer
    networks:
      - test