# Copyright IBM Corp. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

version: '2'

networks:
  test:

services:
  couchdb4:
    container_name: couchdb4
    image: couchdb:3.1.1
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "6984:5984"
    networks:
      - test

  couchdb5:
    container_name: couchdb5
    image: couchdb:3.1.1
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "7984:5984"
    networks:
      - test